### PR TITLE
No color

### PR DESCRIPTION
**Pull request by hcaltenco**
Branch with only updates related to the axis definition. Without color support which causes problems in rovioli for some reason.

### CODE REVIEW

**Comment by chutsu** [comment]
Sorry I missed this, ROVILI needs RGB?

**Comment by hcaltenco** [comment]
Hi Chrostopher,

 

No, quite the opposite. 😊, We forked a copy of your repo  and modified the coordinate definition and added RGB stream ( <https://github.com/hcaltenco/rs4se/tree/master> https://github.com/hcaltenco/rs4se/tree/master). We used it for object detection, which needs RGB. But the RGB stream caused problems with ROVIOLI, so I created a branch of the forked repo without the RGB, only the other fixes ( <https://github.com/hcaltenco/rs4se/tree/no-color> https://github.com/hcaltenco/rs4se/tree/no-color).

 

So far we are running with two cameras, one for object detection and one for ROVIOLI. 

 

We will work on a fix to run with only one camera (and have RGB and depth streams).

**Comment by chutsu** [comment]
Ok, yeah for ROVIO you don't want to use the RGB stream because it is rolling shutter. It is incredibly susceptible to motion blur causing VIO algorithms like ROVIO to not give good results. Instead you should run it against the **two IR cameras with the IR emmitter switched off**.

The original intension for `rs4se` was just for VIO only* but I'm beginning to see a fair few people are begging to use the RealSense for object detection as well. I am currently opening up the RGB stream (stole bits of your code) as well as the depth.

**Comment by hcaltenco** [comment]
Hi Christopher,

 

Indeed, we use RS4SE with IR camera and IMU for ROVIO since it gives good results.  The problem of not including RGB and depth are that if you want to use two different ROS wrappers, then you need two cameras. And switch off the IR emitter on the second camera too, otherwise it will disturb  the first camera. But would be great if one could use RS4SE for both tasks, Object detection, depth estimation and VIO. 

 

Feel free to use the RGB parts of the code for merging into your new implementation.

**Pull request closed without merging**
